// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqg_NTiAd3j42CZ-0Pnb5s5TeYz8IoZcw',
    appId: '1:1043094660763:web:56170f468b7ea34704483e',
    messagingSenderId: '1043094660763',
    projectId: 'mindmates-b97a0',
    authDomain: 'mindmates-b97a0.firebaseapp.com',
    storageBucket: 'mindmates-b97a0.appspot.com',
    measurementId: 'G-S0XSF9E158',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOY-fROsMbrIRwuYmBNRhrhx86gWL_hYM',
    appId: '1:1043094660763:android:93bc395395f1ab9704483e',
    messagingSenderId: '1043094660763',
    projectId: 'mindmates-b97a0',
    storageBucket: 'mindmates-b97a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYufOf8BYOsKhOURw3AnyqGZvGCfDujvY',
    appId: '1:1043094660763:ios:107f1e552dacdf7004483e',
    messagingSenderId: '1043094660763',
    projectId: 'mindmates-b97a0',
    storageBucket: 'mindmates-b97a0.appspot.com',
    iosBundleId: 'com.example.mindmates2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYufOf8BYOsKhOURw3AnyqGZvGCfDujvY',
    appId: '1:1043094660763:ios:107f1e552dacdf7004483e',
    messagingSenderId: '1043094660763',
    projectId: 'mindmates-b97a0',
    storageBucket: 'mindmates-b97a0.appspot.com',
    iosBundleId: 'com.example.mindmates2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqg_NTiAd3j42CZ-0Pnb5s5TeYz8IoZcw',
    appId: '1:1043094660763:web:75a7709722b74c2b04483e',
    messagingSenderId: '1043094660763',
    projectId: 'mindmates-b97a0',
    authDomain: 'mindmates-b97a0.firebaseapp.com',
    storageBucket: 'mindmates-b97a0.appspot.com',
    measurementId: 'G-EBSRWXY88J',
  );
}
